In [46]:
import pandas as pd
from numpy import *
import numpy as np
from sklearn import preprocessing
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import metrics
#from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
from sklearn import neighbors

In [47]:
#Input as training data
data =pd.read_csv('train.csv')
array = data.values
array

array([['Male', 17, 7, ..., 3, 2, 'extraverted'],
       ['Male', 19, 4, ..., 6, 6, 'serious'],
       ['Female', 18, 7, ..., 5, 5, 'dependable'],
       ...,
       ['Male', 22, 5, ..., 6, 1, 'serious'],
       ['Male', 19, 5, ..., 7, 5, 'extraverted'],
       ['Female', 18, 5, ..., 6, 5, 'extraverted']], dtype=object)

In [48]:
# Displaying training data
data

Gender  Age  openness  neuroticism  conscientiousness  agreeableness  \
0      Male   17         7            4                  7              3   
1      Male   19         4            5                  4              6   
2    Female   18         7            6                  4              5   
3    Female   22         5            6                  7              4   
4    Female   19         7            4                  6              5   
..      ...  ...       ...          ...                ...            ...   
704  Female   20         4            5                  6              6   
705    Male   18         6            3                  1              5   
706    Male   22         5            2                  3              6   
707    Male   19         5            6                  5              7   
708  Female   18         5            5                  7              6   

     extraversion Personality (Class label)  
0               2               extraverted  
1               6                   serious  
2               5                dependable  
3               3               extraverted  
4               4                    lively  
..            ...                       ...  
704             1               responsible  
705             5                dependable  
706             1                   serious  
707             5               extraverted  
708             5               extraverted  

[709 rows x 8 columns]

In [49]:
#Preprocessing
#Converting Categorical to numerical value
for i in range(len(array)):#[row],[col]
	if array[i][0]=="Male":
		array[i][0]=1
	else:
		array[i][0]=0

In [50]:
#Result of conversion
df=pd.DataFrame(array)
df

0   1  2  3  4  5  6            7
0    1  17  7  4  7  3  2  extraverted
1    1  19  4  5  4  6  6      serious
2    0  18  7  6  4  5  5   dependable
3    0  22  5  6  7  4  3  extraverted
4    0  19  7  4  6  5  4       lively
..  ..  .. .. .. .. .. ..          ...
704  0  20  4  5  6  6  1  responsible
705  1  18  6  3  1  5  5   dependable
706  1  22  5  2  3  6  1      serious
707  1  19  5  6  5  7  5  extraverted
708  0  18  5  5  7  6  5  extraverted

[709 rows x 8 columns]

In [51]:
#features extraction
maindf =df[[0,1,2,3,4,5,6]]
mainarray=maindf.values
print (mainarray)

[[1 17 7 ... 7 3 2]
 [1 19 4 ... 4 6 6]
 [0 18 7 ... 4 5 5]
 ...
 [1 22 5 ... 3 6 1]
 [1 19 5 ... 5 7 5]
 [0 18 5 ... 7 6 5]]


In [52]:
#labels 
temp=df[7]
train_y =temp.values
train_y

array(['extraverted', 'serious', 'dependable', 'extraverted', 'lively',
       'lively', 'extraverted', 'extraverted', 'dependable', 'lively',
       'serious', 'extraverted', 'lively', 'dependable', 'responsible',
       'extraverted', 'serious', 'dependable', 'responsible',
       'extraverted', 'responsible', 'extraverted', 'responsible',
       'serious', 'serious', 'dependable', 'extraverted', 'extraverted',
       'lively', 'lively', 'extraverted', 'extraverted', 'dependable',
       'lively', 'serious', 'lively', 'responsible', 'responsible',
       'dependable', 'serious', 'dependable', 'extraverted', 'serious',
       'extraverted', 'dependable', 'dependable', 'responsible',
       'serious', 'lively', 'lively', 'extraverted', 'extraverted',
       'serious', 'extraverted', 'lively', 'lively', 'extraverted',
       'dependable', 'lively', 'lively', 'responsible', 'extraverted',
       'responsible', 'dependable', 'serious', 'serious', 'responsible',
       'dependable', 'respo

In [53]:
for i in range(len(train_y)):
	train_y[i] =str(train_y[i])

In [54]:
from sklearn.ensemble import BaggingClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
pipeline = make_pipeline(StandardScaler(), LogisticRegression(random_state=1))
bgclassifier = BaggingClassifier(base_estimator=pipeline, n_estimators=100, max_samples=100, random_state=1, n_jobs=5)
bgclassifier.fit(mainarray, train_y)

BaggingClassifier(base_estimator=Pipeline(steps=[('standardscaler',
                                                  StandardScaler()),
                                                 ('logisticregression',
                                                  LogisticRegression(random_state=1))]),
                  max_samples=100, n_estimators=100, n_jobs=5, random_state=1)

In [55]:
#Getting test data
testdata =pd.read_csv('test dataset.csv')
test = testdata.values
testdata

Gender  Age  openness  neuroticism  conscientiousness  agreeableness  \
0    Female   20         7            9                  9              5   
1      Male   17         5            4                  5              2   
2    Female   25         5            5                  7              2   
3    Female   18         6            2                  7              4   
4    Female   19         2            4                  7              1   
..      ...  ...       ...          ...                ...            ...   
310  Female   19         6            5                  6              4   
311    Male   18         2            5                  8              3   
312    Male   18         7            5                  6              2   
313    Male   23         6            7                  5              4   
314  Female   18         5            7                  3              5   

     extraversion Personality (class label)  
0               5                dependable  
1               4                   serious  
2               4                   serious  
3               7                   serious  
4               3               responsible  
..            ...                       ...  
310             3               extraverted  
311             7                dependable  
312             7                   serious  
313             3               extraverted  
314             6               extraverted  

[315 rows x 8 columns]

In [56]:
#Preprocessing
#Converting Categorical to numerical value
for i in range(len(test)):
	if test[i][0]=="Male":
		test[i][0]=1
	else:
		test[i][0]=0

In [57]:
df1=pd.DataFrame(test)
df1

0   1  2  3  4  5  6            7
0    0  20  7  9  9  5  5   dependable
1    1  17  5  4  5  2  4      serious
2    0  25  5  5  7  2  4      serious
3    0  18  6  2  7  4  7      serious
4    0  19  2  4  7  1  3  responsible
..  ..  .. .. .. .. .. ..          ...
310  0  19  6  5  6  4  3  extraverted
311  1  18  2  5  8  3  7   dependable
312  1  18  7  5  6  2  7      serious
313  1  23  6  7  5  4  3  extraverted
314  0  18  5  7  3  5  6  extraverted

[315 rows x 8 columns]

In [58]:
#features 
testdf =df1[[0,1,2,3,4,5,6]]
maintestarray=testdf.values
print(maintestarray)

[[0 20 7 ... 9 5 5]
 [1 17 5 ... 5 2 4]
 [0 25 5 ... 7 2 4]
 ...
 [1 18 7 ... 6 2 7]
 [1 23 6 ... 5 4 3]
 [0 18 5 ... 3 5 6]]


In [59]:
test_out =df1[[7]]
test_out_array=test_out.values
test_out_array

array([['dependable'],
       ['serious'],
       ['serious'],
       ['serious'],
       ['responsible'],
       ['serious'],
       ['extraverted'],
       ['serious'],
       ['serious'],
       ['serious'],
       ['serious'],
       ['responsible'],
       ['responsible'],
       ['serious'],
       ['lively'],
       ['extraverted'],
       ['serious'],
       ['serious'],
       ['serious'],
       ['extraverted'],
       ['serious'],
       ['dependable'],
       ['serious'],
       ['extraverted'],
       ['extraverted'],
       ['serious'],
       ['extraverted'],
       ['dependable'],
       ['serious'],
       ['responsible'],
       ['serious'],
       ['lively'],
       ['extraverted'],
       ['lively'],
       ['serious'],
       ['serious'],
       ['serious'],
       ['serious'],
       ['extraverted'],
       ['serious'],
       ['responsible'],
       ['responsible'],
       ['serious'],
       ['extraverted'],
       ['dependable'],
       ['serious'],
       ['re

In [60]:
#Predicting Personality
y_pred = bgclassifier.predict(maintestarray)
for i in range(len(y_pred)) :
	y_pred[i]=str((y_pred[i]))
	print("Personality for Person No "+str(i)+" is " + y_pred[i])
DF = pd.DataFrame(y_pred,columns=['Predicted Personality'])
DF.index=DF.index+1
DF.index.names = ['Person No']
DF.to_csv("output.csv")

Personality for Person No 0 is extraverted
Personality for Person No 1 is serious
Personality for Person No 2 is dependable
Personality for Person No 3 is serious
Personality for Person No 4 is responsible
Personality for Person No 5 is serious
Personality for Person No 6 is responsible
Personality for Person No 7 is serious
Personality for Person No 8 is serious
Personality for Person No 9 is serious
Personality for Person No 10 is serious
Personality for Person No 11 is responsible
Personality for Person No 12 is responsible
Personality for Person No 13 is serious
Personality for Person No 14 is responsible
Personality for Person No 15 is extraverted
Personality for Person No 16 is serious
Personality for Person No 17 is serious
Personality for Person No 18 is serious
Personality for Person No 19 is extraverted
Personality for Person No 20 is serious
Personality for Person No 21 is extraverted
Personality for Person No 22 is serious
Personality for Person No 23 is serious
Personality

In [61]:
from sklearn.metrics  import accuracy_score 

In [62]:
ac =accuracy_score(y_pred,test_out_array)
print("accuracy = ",round(ac*100,2),'%')

accuracy =  75.87 %
